#!/usr/bin/env python

import fileinput
import json
import signal

signal.signal(signal.SIGPIPE, signal.SIG_DFL)

headers = None
for line in fileinput.input(encoding="utf-8"):
    if line.strip() == '':
        continue
    row = json.loads(line)
    if headers is None:
        headers = list(row.keys())
        print('#' + ' '.join(json.dumps(key) for key in headers))
    else:
        assert list(row.keys()) == headers

    print(' '.join(json.dumps(value) for value in row.values()))

